# Generated by Django 4.2.3 on 2023-07-15 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_responses_alter_justcontact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justcontact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 15, 16, 31, 56, 285350)),
        ),
    ]
