# Generated by Django 4.2.3 on 2023-07-15 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_justcontact_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='image',
            field=models.ImageField(default='image', upload_to=''),
        ),
        migrations.AlterField(
            model_name='justcontact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 15, 16, 37, 27, 621337)),
        ),
    ]
