# Generated by Django 4.2.3 on 2023-07-20 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_products_alter_blog_file_alter_blog_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justcontact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 20, 23, 17, 55, 17026)),
        ),
        migrations.AlterField(
            model_name='products',
            name='desc',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='products',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 20, 23, 17, 55, 19028)),
        ),
    ]
