# Generated by Django 4.2.3 on 2023-07-24 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_contact_alter_justcontact_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('json_data', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=15)),
                ('address', models.CharField(max_length=500)),
                ('address2', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=50)),
                ('addressType', models.CharField(max_length=10)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2023, 7, 24, 20, 24, 42, 529568, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.AlterField(
            model_name='justcontact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 1, 54, 42, 526569)),
        ),
        migrations.AlterField(
            model_name='products',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 1, 54, 42, 528568)),
        ),
    ]
