# Generated by Django 4.2.3 on 2023-07-24 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_justcontact_date_alter_orders_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justcontact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 2, 28, 23, 988088)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='addressType',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='orders',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 2, 28, 23, 991087)),
        ),
        migrations.AlterField(
            model_name='products',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 2, 28, 23, 990090)),
        ),
    ]
