# Generated by Django 4.2.3 on 2023-07-24 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_justcontact_date_alter_orders_addresstype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justcontact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 2, 34, 12, 678229)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 2, 34, 12, 680229)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='json_data',
            field=models.CharField(default={}, max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 2, 34, 12, 679229)),
        ),
    ]
