# Generated by Django 4.2.3 on 2023-07-24 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_justcontact_date_alter_orders_datetime_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterField(
            model_name='justcontact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 3, 29, 3, 740435)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 3, 29, 3, 743435)),
        ),
        migrations.AlterField(
            model_name='products',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 3, 29, 3, 741435)),
        ),
    ]
