# Generated by Django 4.2.3 on 2023-07-29 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_orderupdates_alter_orders_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderupdates',
            options={'verbose_name': 'Order Updates', 'verbose_name_plural': 'Order Updates'},
        ),
        migrations.AlterField(
            model_name='justcontact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 29, 16, 40, 52, 307350)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 29, 16, 40, 52, 310350)),
        ),
        migrations.AlterField(
            model_name='products',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 29, 16, 40, 52, 308350)),
        ),
    ]
